version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: example
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
  
  noip:
    image:  coppit/no-ip
    volumes:
      - noip-config:/config
      - noip-etc:/etc
    
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    volumes:
     - openvpn-data:/etc/openvpn
  
  node:
    image: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs/Historiador:/home/node/app
    command: "npm run server"
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
    


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    


volumes:
  db-data:
  pgadmin-data:
  openvpn-data:
  noip-config:
  noip-etc:
  
  mongodb-data:

  
  
